uploads = []
outputs = []

[[generated]]
id = "UHXZWmde7NvThUMRTyU2u"
uri = "file://imgs/blue_dream.png"
type = "image"
title = "generated_image"

[[generated]]
id = "hxflwGEN-oqcot8vY9pDx"
uri = "file://imgs/og_kush.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Aj1erU_RmpBJL9zIYnX60"
uri = "file://imgs/girl_scout_cookies.png"
type = "image"
title = "generated_image"

[[generated]]
id = "IXdyaY9u965VWVM3aJ_UH"
uri = "file://imgs/gorilla_glue4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "uptOiTBzCSfNoZw_ktvF_"
uri = "file://imgs/sour_diesel.png"
type = "image"
title = "generated_image"

[[generated]]
id = "xeHTktC1z7EFeVIVvY8rB"
uri = "file://imgs/purple_punch.png"
type = "image"
title = "generated_image"

[[generated]]
id = "x1lvhc12CEBdQvErBOYVo"
uri = "file://imgs/wedding_cake.png"
type = "image"
title = "generated_image"

[[generated]]
id = "WEECkkxFX5V4cMdzLQhdn"
uri = "file://imgs/zkittlez.png"
type = "image"
title = "generated_image"

[[generated]]
id = "vK7cHx_4QBvnkfhIaFBMl"
uri = "file://imgs/white_widow.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5bgmD3ADBMpSrJdqWpvAv"
uri = "file://imgs/gelato33.png"
type = "image"
title = "generated_image"

[[generated]]
id = "fgkAOx7PDv4U4ZpkEtCrg"
uri = "file://imgs/hero_flower.png"
type = "image"
title = "hero flower banner"

[[generated]]
id = "0GJR3SzOHJW3tnrIc5NEQ"
uri = "file://imgs/prod_concentrate_new.png"
type = "image"
title = "concentrate product photo"

[[generated]]
id = "60epweMtdo-c0JjWjHaEF"
uri = "file://imgs/prod_preroll_new.png"
type = "image"
title = "pre-roll product photo"

[[generated]]
id = "pr-xXYG9fbtLWCdf6rDMv"
uri = "file://imgs/prod_hash_new.png"
type = "image"
title = "hash product photo"

[[generated]]
id = "7TSmpeP485uV6cI3f9zXH"
uri = "file://imgs/prod_seeds_new.png"
type = "image"
title = "cannabis seeds product"

[[generated]]
id = "5vRK_QNAuZ3pU-QMskQvI"
uri = "file://imgs/prod_oils_new.png"
type = "image"
title = "cbd oil tincture product"

[[generated]]
id = "2IdywK4LHN8mlNK85Yv4N"
uri = "file://imgs/pack_blue_dream.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gx1XkhuISQPXv-ayhORjO"
uri = "file://imgs/pack_og_kush.png"
type = "image"
title = "generated_image"

[[generated]]
id = "X5kV2uKnMzlEXpFB4zqZh"
uri = "file://imgs/pack_gsc.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ddGC316Ih1OgmyDOTUDVh"
uri = "file://imgs/pack_gorilla_glue.png"
type = "image"
title = "generated_image"

[[generated]]
id = "3xwng0Mi1fd5L-MlhMlRA"
uri = "file://imgs/pack_sour_diesel.png"
type = "image"
title = "generated_image"

[[generated]]
id = "sqnU6piAstfupqkelttJ2"
uri = "file://imgs/pack_purple_punch.png"
type = "image"
title = "generated_image"

[[generated]]
id = "joNnTwUi__G4JdY422pKb"
uri = "file://imgs/pack_wedding_cake.png"
type = "image"
title = "generated_image"

[[generated]]
id = "AVaKo1j1VqbP857JmyziC"
uri = "file://imgs/pack_zkittlez.png"
type = "image"
title = "generated_image"

[[generated]]
id = "kNr9Ykd3dE75q4AApFFyr"
uri = "file://imgs/pack_white_widow.png"
type = "image"
title = "generated_image"

[[generated]]
id = "SgfvAidY528tZ0aRtqZzP"
uri = "file://imgs/pack_gelato33.png"
type = "image"
title = "generated_image"

[[generated]]
id = "iisLpF5yGvWXnuwFwUUKu"
uri = "file://imgs/pack_concentrate.png"
type = "image"
title = "generated_image"

[[generated]]
id = "v9TypcgxyUJjKPQgIeMPc"
uri = "file://imgs/pack_hash.png"
type = "image"
title = "generated_image"

[[generated]]
id = "WzH8Ma4OdJrfz02FNN-X_"
uri = "file://imgs/pack_preroll.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ecTZwxDozLl1EEmEvKY_p"
uri = "file://imgs/pack_tincture.png"
type = "image"
title = "generated_image"

[[generated]]
id = "7-aFtFwBAENYMpP1XLVVg"
uri = "file://imgs/pack_cream.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Y-CV_-JIqLyeK2exTBunW"
uri = "file://imgs/pack_grinder.png"
type = "image"
title = "generated_image"
